// Auto-generated by extract.js — 2026-04-29T10:46:12.989Z
const YOM_DATA = {
  "extractedAt": "2026-04-29T10:41:46.692Z",
  "fxRates": {
    "CLP_TO_USD": 0.00111647,
    "COP_TO_USD": 0.00027495
  },
  "clients": [
    {
      "domain": "soprole.youorder.me",
      "name": "Soprole",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 192816,
      "comercios": 10560,
      "comerciosRegistrados": 246088,
      "vendedores": 239,
      "vendedoresYOM": 8,
      "cuentasVendedor": 263,
      "ventaSinIVA": 40462383,
      "primeraOrden": "2021-02-09T19:52:52.720Z",
      "ultimaOrden": "2026-04-29T04:08:32.030Z",
      "mensual": [
        {
          "year": 2025,
          "month": 4,
          "ordenes": 335,
          "ventaSinIVA": 69531,
          "comerciosActivos": 330,
          "vendedoresActivos": 134
        },
        {
          "year": 2025,
          "month": 5,
          "ordenes": 6313,
          "ventaSinIVA": 1299045,
          "comerciosActivos": 2548,
          "vendedoresActivos": 182
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 6350,
          "ventaSinIVA": 1237337,
          "comerciosActivos": 2664,
          "vendedoresActivos": 185
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 7252,
          "ventaSinIVA": 1484752,
          "comerciosActivos": 2836,
          "vendedoresActivos": 188
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 7259,
          "ventaSinIVA": 1434889,
          "comerciosActivos": 2914,
          "vendedoresActivos": 211
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 6799,
          "ventaSinIVA": 1458975,
          "comerciosActivos": 2909,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 7548,
          "ventaSinIVA": 1475857,
          "comerciosActivos": 2914,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 6962,
          "ventaSinIVA": 1388474,
          "comerciosActivos": 2851,
          "vendedoresActivos": 212
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 6819,
          "ventaSinIVA": 1368207,
          "comerciosActivos": 2819,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 7121,
          "ventaSinIVA": 1384869,
          "comerciosActivos": 2931,
          "vendedoresActivos": 219
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6833,
          "ventaSinIVA": 1384023,
          "comerciosActivos": 2954,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 7866,
          "ventaSinIVA": 1481749,
          "comerciosActivos": 3061,
          "vendedoresActivos": 221
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6992,
          "ventaSinIVA": 1345874,
          "comerciosActivos": 2952,
          "vendedoresActivos": 227
        }
      ]
    },
    {
      "domain": "codelpa.youorder.me",
      "name": "Codelpa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 120414,
      "comercios": 2822,
      "comerciosRegistrados": 6882,
      "vendedores": 34,
      "vendedoresYOM": 22,
      "cuentasVendedor": 855,
      "ventaSinIVA": 151594811,
      "primeraOrden": "2020-06-01T20:36:18.883Z",
      "ultimaOrden": "2026-04-29T06:22:21.759Z",
      "mensual": [
        {
          "year": 2025,
          "month": 4,
          "ordenes": 9,
          "ventaSinIVA": 6827,
          "comerciosActivos": 7,
          "vendedoresActivos": 8
        },
        {
          "year": 2025,
          "month": 5,
          "ordenes": 1036,
          "ventaSinIVA": 1322093,
          "comerciosActivos": 581,
          "vendedoresActivos": 23
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 1256,
          "ventaSinIVA": 1593182,
          "comerciosActivos": 628,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1467,
          "ventaSinIVA": 2083768,
          "comerciosActivos": 719,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1585,
          "ventaSinIVA": 2438034,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1536,
          "ventaSinIVA": 1853397,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 1806,
          "ventaSinIVA": 2392699,
          "comerciosActivos": 773,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 1802,
          "ventaSinIVA": 2595952,
          "comerciosActivos": 769,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 1801,
          "ventaSinIVA": 2559148,
          "comerciosActivos": 768,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 1797,
          "ventaSinIVA": 2673617,
          "comerciosActivos": 733,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1559,
          "ventaSinIVA": 2344409,
          "comerciosActivos": 687,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1872,
          "ventaSinIVA": 2934880,
          "comerciosActivos": 774,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1417,
          "ventaSinIVA": 2224067,
          "comerciosActivos": 681,
          "vendedoresActivos": 22
        }
      ]
    },
    {
      "domain": "codelpa-peru.youorder.me",
      "name": "Codelpa Perú",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "softys-cencocal.youorder.me",
      "name": "Softys-Cencocal",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 923123,
      "comercios": 18392,
      "comerciosRegistrados": 28952,
      "vendedores": 79,
      "vendedoresYOM": 2,
      "cuentasVendedor": 59,
      "ventaSinIVA": 74317399,
      "primeraOrden": "2021-10-14T16:10:20.000Z",
      "ultimaOrden": "2026-04-28T21:58:49.547Z",
      "mensual": [
        {
          "year": 2025,
          "month": 4,
          "ordenes": 1702,
          "ventaSinIVA": 110892,
          "comerciosActivos": 1673,
          "vendedoresActivos": 48
        },
        {
          "year": 2025,
          "month": 5,
          "ordenes": 21010,
          "ventaSinIVA": 1773871,
          "comerciosActivos": 9490,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 20459,
          "ventaSinIVA": 1690978,
          "comerciosActivos": 9406,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 22245,
          "ventaSinIVA": 1805183,
          "comerciosActivos": 9615,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 20703,
          "ventaSinIVA": 1712588,
          "comerciosActivos": 9602,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 20331,
          "ventaSinIVA": 1775312,
          "comerciosActivos": 9369,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 22245,
          "ventaSinIVA": 1756095,
          "comerciosActivos": 9460,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 19517,
          "ventaSinIVA": 1511587,
          "comerciosActivos": 9392,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 20442,
          "ventaSinIVA": 1716703,
          "comerciosActivos": 9301,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 20863,
          "ventaSinIVA": 1808043,
          "comerciosActivos": 9503,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 18629,
          "ventaSinIVA": 1621731,
          "comerciosActivos": 8890,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 20520,
          "ventaSinIVA": 1675093,
          "comerciosActivos": 9330,
          "vendedoresActivos": 49
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 17266,
          "ventaSinIVA": 1436325,
          "comerciosActivos": 8923,
          "vendedoresActivos": 51
        }
      ]
    },
    {
      "domain": "softys-dimak.youorder.me",
      "name": "Dimak",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "surtiventas.youorder.me",
      "name": "Surtiventas",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 95128,
      "comercios": 10721,
      "comerciosRegistrados": 11204,
      "vendedores": 77,
      "vendedoresYOM": 2,
      "cuentasVendedor": 91,
      "ventaSinIVA": 29072497,
      "primeraOrden": "2025-06-18T15:17:44.387Z",
      "ultimaOrden": "2026-04-29T02:37:03.579Z",
      "mensual": [
        {
          "year": 2025,
          "month": 6,
          "ordenes": 75,
          "ventaSinIVA": 68045,
          "comerciosActivos": 71,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 967,
          "ventaSinIVA": 95300,
          "comerciosActivos": 764,
          "vendedoresActivos": 5
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1122,
          "ventaSinIVA": 246799,
          "comerciosActivos": 648,
          "vendedoresActivos": 12
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 3506,
          "ventaSinIVA": 885557,
          "comerciosActivos": 2155,
          "vendedoresActivos": 32
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 9846,
          "ventaSinIVA": 2041874,
          "comerciosActivos": 5136,
          "vendedoresActivos": 60
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 11451,
          "ventaSinIVA": 3524030,
          "comerciosActivos": 5807,
          "vendedoresActivos": 63
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 12330,
          "ventaSinIVA": 4361983,
          "comerciosActivos": 6108,
          "vendedoresActivos": 66
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 13151,
          "ventaSinIVA": 5187776,
          "comerciosActivos": 6579,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 12003,
          "ventaSinIVA": 4063265,
          "comerciosActivos": 5903,
          "vendedoresActivos": 65
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 16968,
          "ventaSinIVA": 5160070,
          "comerciosActivos": 7212,
          "vendedoresActivos": 61
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 13709,
          "ventaSinIVA": 3437797,
          "comerciosActivos": 6813,
          "vendedoresActivos": 63
        }
      ]
    },
    {
      "domain": "elmuneco.youorder.me",
      "name": "El Muñeco",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 2761,
      "comercios": 881,
      "comerciosRegistrados": 7625,
      "vendedores": 10,
      "vendedoresYOM": 2,
      "cuentasVendedor": 16,
      "ventaSinIVA": 193189,
      "primeraOrden": "2025-07-02T20:14:49.488Z",
      "ultimaOrden": "2026-04-28T16:56:20.535Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1,
          "ventaSinIVA": 52,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 142,
          "ventaSinIVA": 8913,
          "comerciosActivos": 112,
          "vendedoresActivos": 2
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 16,
          "ventaSinIVA": 768,
          "comerciosActivos": 16,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 4,
          "ventaSinIVA": 136,
          "comerciosActivos": 1,
          "vendedoresActivos": 1
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 8,
          "ventaSinIVA": 665,
          "comerciosActivos": 7,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 30,
          "ventaSinIVA": 2511,
          "comerciosActivos": 25,
          "vendedoresActivos": 3
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 230,
          "ventaSinIVA": 15935,
          "comerciosActivos": 213,
          "vendedoresActivos": 6
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1285,
          "ventaSinIVA": 96277,
          "comerciosActivos": 639,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 762,
          "ventaSinIVA": 52660,
          "comerciosActivos": 469,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 283,
          "ventaSinIVA": 15273,
          "comerciosActivos": 157,
          "vendedoresActivos": 2
        }
      ]
    },
    {
      "domain": "marleycoffee.youorder.me",
      "name": "Marley Coffee",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 329,
      "comercios": 59,
      "comerciosRegistrados": 2832,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 57,
      "ventaSinIVA": 207392,
      "primeraOrden": "2025-07-15T21:53:35.185Z",
      "ultimaOrden": "2026-04-28T21:07:05.120Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 14,
          "ventaSinIVA": 11181,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 2,
          "ventaSinIVA": 1025,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 2629,
          "comerciosActivos": 3,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 25,
          "ventaSinIVA": 22433,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 49,
          "ventaSinIVA": 34672,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 47,
          "ventaSinIVA": 31225,
          "comerciosActivos": 15,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 30,
          "ventaSinIVA": 20512,
          "comerciosActivos": 14,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 57,
          "ventaSinIVA": 38150,
          "comerciosActivos": 17,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 102,
          "ventaSinIVA": 45565,
          "comerciosActivos": 54,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisa.youorder.me",
      "name": "Prisa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "caren.youorder.me",
      "name": "Caren",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "coexito.youorder.me",
      "name": "CoÉxito",
      "currency": "USD",
      "nativeCurrency": "COP",
      "sinDatos": false,
      "ordenes": 26640,
      "comercios": 5462,
      "comerciosRegistrados": 22924,
      "vendedores": 92,
      "vendedoresYOM": 0,
      "cuentasVendedor": 141,
      "ventaSinIVA": 25020330,
      "primeraOrden": "2025-11-12T21:55:34.073Z",
      "ultimaOrden": "2026-04-29T03:03:34.202Z",
      "mensual": [
        {
          "year": 2025,
          "month": 11,
          "ordenes": 34,
          "ventaSinIVA": 22066,
          "comerciosActivos": 23,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 763,
          "ventaSinIVA": 742260,
          "comerciosActivos": 365,
          "vendedoresActivos": 10
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 2278,
          "ventaSinIVA": 2604872,
          "comerciosActivos": 1273,
          "vendedoresActivos": 40
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6794,
          "ventaSinIVA": 6382841,
          "comerciosActivos": 3323,
          "vendedoresActivos": 87
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 9253,
          "ventaSinIVA": 8868141,
          "comerciosActivos": 3721,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 7518,
          "ventaSinIVA": 6400150,
          "comerciosActivos": 3576,
          "vendedoresActivos": 85
        }
      ]
    },
    {
      "domain": "bastien.youorder.me",
      "name": "Bastien",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "sonrie.youorder.me",
      "name": "Sonrie",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 10,
      "comercios": 3,
      "comerciosRegistrados": 2166,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 1,
      "ventaSinIVA": 187,
      "primeraOrden": "2025-09-30T18:05:34.310Z",
      "ultimaOrden": "2026-04-23T19:05:57.930Z",
      "mensual": [
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1,
          "ventaSinIVA": 12,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 76,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6,
          "ventaSinIVA": 100,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "expressdent.youorder.me",
      "name": "ExpressDent",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 6,
      "comercios": 4,
      "comerciosRegistrados": 13560,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 30,
      "ventaSinIVA": 102,
      "primeraOrden": "2026-01-06T19:43:36.968Z",
      "ultimaOrden": "2026-02-05T19:56:42.097Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 5,
          "ventaSinIVA": 102,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1,
          "ventaSinIVA": 1,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisur.youorder.me",
      "name": "Prisur",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 3850,
      "comercios": 1340,
      "comerciosRegistrados": 10769,
      "vendedores": 32,
      "vendedoresYOM": 2,
      "cuentasVendedor": 44,
      "ventaSinIVA": 571097,
      "primeraOrden": "2026-01-20T14:59:35.680Z",
      "ultimaOrden": "2026-04-29T00:13:33.169Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 89,
          "ventaSinIVA": 10400,
          "comerciosActivos": 64,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1034,
          "ventaSinIVA": 150839,
          "comerciosActivos": 665,
          "vendedoresActivos": 24
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1614,
          "ventaSinIVA": 246139,
          "comerciosActivos": 843,
          "vendedoresActivos": 20
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1113,
          "ventaSinIVA": 163718,
          "comerciosActivos": 728,
          "vendedoresActivos": 21
        }
      ]
    }
  ]
};
