// Auto-generated by extract.js — 2026-05-01T10:40:15.698Z
const YOM_DATA = {
  "extractedAt": "2026-05-01T10:36:05.044Z",
  "fxRates": {
    "CLP_TO_USD": 0.00110059,
    "COP_TO_USD": 0.00027513
  },
  "clients": [
    {
      "domain": "soprole.youorder.me",
      "name": "Soprole",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 193207,
      "comercios": 10567,
      "comerciosRegistrados": 246166,
      "vendedores": 239,
      "vendedoresYOM": 8,
      "cuentasVendedor": 263,
      "ventaSinIVA": 39982329,
      "primeraOrden": "2021-02-09T19:52:52.720Z",
      "ultimaOrden": "2026-05-01T09:01:20.487Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 6301,
          "ventaSinIVA": 1277878,
          "comerciosActivos": 2545,
          "vendedoresActivos": 182
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 6350,
          "ventaSinIVA": 1219738,
          "comerciosActivos": 2664,
          "vendedoresActivos": 185
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 7252,
          "ventaSinIVA": 1463634,
          "comerciosActivos": 2836,
          "vendedoresActivos": 188
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 7259,
          "ventaSinIVA": 1414480,
          "comerciosActivos": 2914,
          "vendedoresActivos": 211
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 6799,
          "ventaSinIVA": 1438224,
          "comerciosActivos": 2909,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 7548,
          "ventaSinIVA": 1454865,
          "comerciosActivos": 2914,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 6962,
          "ventaSinIVA": 1368725,
          "comerciosActivos": 2851,
          "vendedoresActivos": 212
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 6819,
          "ventaSinIVA": 1348747,
          "comerciosActivos": 2819,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 7121,
          "ventaSinIVA": 1365172,
          "comerciosActivos": 2931,
          "vendedoresActivos": 219
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6833,
          "ventaSinIVA": 1364337,
          "comerciosActivos": 2954,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 7866,
          "ventaSinIVA": 1460674,
          "comerciosActivos": 3061,
          "vendedoresActivos": 221
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 7369,
          "ventaSinIVA": 1417271,
          "comerciosActivos": 2988,
          "vendedoresActivos": 227
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 14,
          "ventaSinIVA": 4919,
          "comerciosActivos": 14,
          "vendedoresActivos": 16
        }
      ]
    },
    {
      "domain": "codelpa.youorder.me",
      "name": "Codelpa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 120576,
      "comercios": 2824,
      "comerciosRegistrados": 6884,
      "vendedores": 34,
      "vendedoresYOM": 22,
      "cuentasVendedor": 855,
      "ventaSinIVA": 149756381,
      "primeraOrden": "2020-06-01T20:36:18.883Z",
      "ultimaOrden": "2026-04-30T23:48:50.777Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 1036,
          "ventaSinIVA": 1303289,
          "comerciosActivos": 581,
          "vendedoresActivos": 23
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 1256,
          "ventaSinIVA": 1570522,
          "comerciosActivos": 628,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1467,
          "ventaSinIVA": 2054130,
          "comerciosActivos": 719,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1585,
          "ventaSinIVA": 2403357,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1536,
          "ventaSinIVA": 1827035,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 1806,
          "ventaSinIVA": 2358667,
          "comerciosActivos": 773,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 1802,
          "ventaSinIVA": 2559029,
          "comerciosActivos": 769,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 1801,
          "ventaSinIVA": 2522749,
          "comerciosActivos": 768,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 1797,
          "ventaSinIVA": 2635589,
          "comerciosActivos": 733,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1559,
          "ventaSinIVA": 2311064,
          "comerciosActivos": 687,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1872,
          "ventaSinIVA": 2893136,
          "comerciosActivos": 774,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1579,
          "ventaSinIVA": 2510196,
          "comerciosActivos": 718,
          "vendedoresActivos": 22
        }
      ]
    },
    {
      "domain": "codelpa-peru.youorder.me",
      "name": "Codelpa Perú",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "softys-cencocal.youorder.me",
      "name": "Softys-Cencocal",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 924736,
      "comercios": 18405,
      "comerciosRegistrados": 28963,
      "vendedores": 79,
      "vendedoresYOM": 2,
      "cuentasVendedor": 59,
      "ventaSinIVA": 73374549,
      "primeraOrden": "2021-10-14T16:10:20.000Z",
      "ultimaOrden": "2026-04-30T18:04:57.003Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 21010,
          "ventaSinIVA": 1748640,
          "comerciosActivos": 9490,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 20459,
          "ventaSinIVA": 1666927,
          "comerciosActivos": 9406,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 22245,
          "ventaSinIVA": 1779508,
          "comerciosActivos": 9615,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 20703,
          "ventaSinIVA": 1688230,
          "comerciosActivos": 9602,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 20331,
          "ventaSinIVA": 1750061,
          "comerciosActivos": 9369,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 22245,
          "ventaSinIVA": 1731118,
          "comerciosActivos": 9460,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 19517,
          "ventaSinIVA": 1490087,
          "comerciosActivos": 9392,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 20442,
          "ventaSinIVA": 1692286,
          "comerciosActivos": 9301,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 20863,
          "ventaSinIVA": 1782327,
          "comerciosActivos": 9503,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 18629,
          "ventaSinIVA": 1598664,
          "comerciosActivos": 8890,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 20520,
          "ventaSinIVA": 1651267,
          "comerciosActivos": 9330,
          "vendedoresActivos": 49
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 18879,
          "ventaSinIVA": 1530092,
          "comerciosActivos": 9085,
          "vendedoresActivos": 51
        }
      ]
    },
    {
      "domain": "softys-dimak.youorder.me",
      "name": "Dimak",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "surtiventas.youorder.me",
      "name": "Surtiventas",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 96372,
      "comercios": 10754,
      "comerciosRegistrados": 11258,
      "vendedores": 77,
      "vendedoresYOM": 2,
      "cuentasVendedor": 91,
      "ventaSinIVA": 28990367,
      "primeraOrden": "2025-06-18T15:17:44.387Z",
      "ultimaOrden": "2026-05-01T03:54:35.144Z",
      "mensual": [
        {
          "year": 2025,
          "month": 6,
          "ordenes": 75,
          "ventaSinIVA": 67077,
          "comerciosActivos": 71,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 967,
          "ventaSinIVA": 93945,
          "comerciosActivos": 764,
          "vendedoresActivos": 5
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1122,
          "ventaSinIVA": 243289,
          "comerciosActivos": 648,
          "vendedoresActivos": 12
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 3506,
          "ventaSinIVA": 872961,
          "comerciosActivos": 2155,
          "vendedoresActivos": 32
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 9846,
          "ventaSinIVA": 2012831,
          "comerciosActivos": 5136,
          "vendedoresActivos": 60
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 11451,
          "ventaSinIVA": 3473907,
          "comerciosActivos": 5807,
          "vendedoresActivos": 63
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 12330,
          "ventaSinIVA": 4299941,
          "comerciosActivos": 6108,
          "vendedoresActivos": 66
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 13151,
          "ventaSinIVA": 5113989,
          "comerciosActivos": 6579,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 12003,
          "ventaSinIVA": 4005472,
          "comerciosActivos": 5903,
          "vendedoresActivos": 65
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 16968,
          "ventaSinIVA": 5086676,
          "comerciosActivos": 7212,
          "vendedoresActivos": 61
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 14940,
          "ventaSinIVA": 3717992,
          "comerciosActivos": 6968,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 13,
          "ventaSinIVA": 2288,
          "comerciosActivos": 13,
          "vendedoresActivos": 2
        }
      ]
    },
    {
      "domain": "elmuneco.youorder.me",
      "name": "El Muñeco",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 2789,
      "comercios": 883,
      "comerciosRegistrados": 7626,
      "vendedores": 10,
      "vendedoresYOM": 2,
      "cuentasVendedor": 16,
      "ventaSinIVA": 191848,
      "primeraOrden": "2025-07-02T20:14:49.488Z",
      "ultimaOrden": "2026-04-30T18:37:04.901Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1,
          "ventaSinIVA": 51,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 142,
          "ventaSinIVA": 8786,
          "comerciosActivos": 112,
          "vendedoresActivos": 2
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 16,
          "ventaSinIVA": 757,
          "comerciosActivos": 16,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 4,
          "ventaSinIVA": 134,
          "comerciosActivos": 1,
          "vendedoresActivos": 1
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 8,
          "ventaSinIVA": 656,
          "comerciosActivos": 7,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 30,
          "ventaSinIVA": 2476,
          "comerciosActivos": 25,
          "vendedoresActivos": 3
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 230,
          "ventaSinIVA": 15708,
          "comerciosActivos": 213,
          "vendedoresActivos": 6
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1285,
          "ventaSinIVA": 94908,
          "comerciosActivos": 639,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 762,
          "ventaSinIVA": 51911,
          "comerciosActivos": 469,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 311,
          "ventaSinIVA": 16462,
          "comerciosActivos": 162,
          "vendedoresActivos": 2
        }
      ]
    },
    {
      "domain": "marleycoffee.youorder.me",
      "name": "Marley Coffee",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 336,
      "comercios": 59,
      "comerciosRegistrados": 2854,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 57,
      "ventaSinIVA": 207530,
      "primeraOrden": "2025-07-15T21:53:35.185Z",
      "ultimaOrden": "2026-04-30T20:41:46.917Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 14,
          "ventaSinIVA": 11022,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 2,
          "ventaSinIVA": 1010,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 2592,
          "comerciosActivos": 3,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 25,
          "ventaSinIVA": 22114,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 49,
          "ventaSinIVA": 34179,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 47,
          "ventaSinIVA": 30781,
          "comerciosActivos": 15,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 30,
          "ventaSinIVA": 20220,
          "comerciosActivos": 14,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 57,
          "ventaSinIVA": 37607,
          "comerciosActivos": 17,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 109,
          "ventaSinIVA": 48004,
          "comerciosActivos": 54,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisa.youorder.me",
      "name": "Prisa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "caren.youorder.me",
      "name": "Caren",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "coexito.youorder.me",
      "name": "CoÉxito",
      "currency": "USD",
      "nativeCurrency": "COP",
      "sinDatos": false,
      "ordenes": 27806,
      "comercios": 5528,
      "comerciosRegistrados": 22937,
      "vendedores": 92,
      "vendedoresYOM": 0,
      "cuentasVendedor": 141,
      "ventaSinIVA": 26808426,
      "primeraOrden": "2025-11-12T21:55:34.073Z",
      "ultimaOrden": "2026-05-01T01:56:49.088Z",
      "mensual": [
        {
          "year": 2025,
          "month": 11,
          "ordenes": 34,
          "ventaSinIVA": 22080,
          "comerciosActivos": 23,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 763,
          "ventaSinIVA": 742746,
          "comerciosActivos": 365,
          "vendedoresActivos": 10
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 2278,
          "ventaSinIVA": 2606578,
          "comerciosActivos": 1273,
          "vendedoresActivos": 40
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6794,
          "ventaSinIVA": 6387019,
          "comerciosActivos": 3323,
          "vendedoresActivos": 87
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 9253,
          "ventaSinIVA": 8873947,
          "comerciosActivos": 3721,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 8668,
          "ventaSinIVA": 8132839,
          "comerciosActivos": 3803,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 16,
          "ventaSinIVA": 43216,
          "comerciosActivos": 16,
          "vendedoresActivos": 6
        }
      ]
    },
    {
      "domain": "bastien.youorder.me",
      "name": "Bastien",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "sonrie.youorder.me",
      "name": "Sonrie",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 10,
      "comercios": 3,
      "comerciosRegistrados": 2166,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 1,
      "ventaSinIVA": 185,
      "primeraOrden": "2025-09-30T18:05:34.310Z",
      "ultimaOrden": "2026-04-23T19:05:57.930Z",
      "mensual": [
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1,
          "ventaSinIVA": 11,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 75,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6,
          "ventaSinIVA": 98,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "expressdent.youorder.me",
      "name": "ExpressDent",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 6,
      "comercios": 4,
      "comerciosRegistrados": 13566,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 30,
      "ventaSinIVA": 101,
      "primeraOrden": "2026-01-06T19:43:36.968Z",
      "ultimaOrden": "2026-02-05T19:56:42.097Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 5,
          "ventaSinIVA": 100,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1,
          "ventaSinIVA": 1,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisur.youorder.me",
      "name": "Prisur",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 3916,
      "comercios": 1349,
      "comerciosRegistrados": 10776,
      "vendedores": 32,
      "vendedoresYOM": 2,
      "cuentasVendedor": 44,
      "ventaSinIVA": 570558,
      "primeraOrden": "2026-01-20T14:59:35.680Z",
      "ultimaOrden": "2026-04-30T23:01:50.982Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 89,
          "ventaSinIVA": 10252,
          "comerciosActivos": 64,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1034,
          "ventaSinIVA": 148694,
          "comerciosActivos": 665,
          "vendedoresActivos": 24
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1614,
          "ventaSinIVA": 242638,
          "comerciosActivos": 843,
          "vendedoresActivos": 20
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1179,
          "ventaSinIVA": 168974,
          "comerciosActivos": 749,
          "vendedoresActivos": 21
        }
      ]
    }
  ]
};
