// Auto-generated by extract.js — 2026-05-05T10:43:17.586Z
const YOM_DATA = {
  "extractedAt": "2026-05-05T10:38:55.088Z",
  "fxRates": {
    "CLP_TO_USD": 0.00111063,
    "COP_TO_USD": 0.00027356
  },
  "clients": [
    {
      "domain": "soprole.youorder.me",
      "name": "Soprole",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 193956,
      "comercios": 10585,
      "comerciosRegistrados": 246305,
      "vendedores": 239,
      "vendedoresYOM": 8,
      "cuentasVendedor": 263,
      "ventaSinIVA": 40474253,
      "primeraOrden": "2021-02-09T19:52:52.720Z",
      "ultimaOrden": "2026-05-05T08:44:41.546Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 5776,
          "ventaSinIVA": 1182179,
          "comerciosActivos": 2487,
          "vendedoresActivos": 181
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 6350,
          "ventaSinIVA": 1230865,
          "comerciosActivos": 2664,
          "vendedoresActivos": 185
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 7252,
          "ventaSinIVA": 1476986,
          "comerciosActivos": 2836,
          "vendedoresActivos": 188
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 7259,
          "ventaSinIVA": 1427384,
          "comerciosActivos": 2914,
          "vendedoresActivos": 211
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 6799,
          "ventaSinIVA": 1451344,
          "comerciosActivos": 2909,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 7548,
          "ventaSinIVA": 1468137,
          "comerciosActivos": 2914,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 6962,
          "ventaSinIVA": 1381211,
          "comerciosActivos": 2851,
          "vendedoresActivos": 212
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 6819,
          "ventaSinIVA": 1361051,
          "comerciosActivos": 2819,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 7121,
          "ventaSinIVA": 1377626,
          "comerciosActivos": 2931,
          "vendedoresActivos": 219
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6833,
          "ventaSinIVA": 1376783,
          "comerciosActivos": 2954,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 7866,
          "ventaSinIVA": 1473998,
          "comerciosActivos": 3061,
          "vendedoresActivos": 221
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 7369,
          "ventaSinIVA": 1430200,
          "comerciosActivos": 2988,
          "vendedoresActivos": 227
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 763,
          "ventaSinIVA": 132155,
          "comerciosActivos": 747,
          "vendedoresActivos": 208
        }
      ]
    },
    {
      "domain": "codelpa.youorder.me",
      "name": "Codelpa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 120629,
      "comercios": 2825,
      "comerciosRegistrados": 6888,
      "vendedores": 34,
      "vendedoresYOM": 22,
      "cuentasVendedor": 856,
      "ventaSinIVA": 151223597,
      "primeraOrden": "2020-06-01T20:36:18.883Z",
      "ultimaOrden": "2026-05-05T00:27:00.573Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 1034,
          "ventaSinIVA": 1314673,
          "comerciosActivos": 580,
          "vendedoresActivos": 23
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 1256,
          "ventaSinIVA": 1584849,
          "comerciosActivos": 628,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1467,
          "ventaSinIVA": 2072869,
          "comerciosActivos": 719,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1585,
          "ventaSinIVA": 2425281,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1536,
          "ventaSinIVA": 1843702,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 1806,
          "ventaSinIVA": 2380183,
          "comerciosActivos": 773,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 1802,
          "ventaSinIVA": 2582373,
          "comerciosActivos": 769,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 1801,
          "ventaSinIVA": 2545762,
          "comerciosActivos": 768,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 1797,
          "ventaSinIVA": 2659632,
          "comerciosActivos": 733,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1559,
          "ventaSinIVA": 2332146,
          "comerciosActivos": 687,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1872,
          "ventaSinIVA": 2919529,
          "comerciosActivos": 774,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1582,
          "ventaSinIVA": 2534784,
          "comerciosActivos": 718,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 50,
          "ventaSinIVA": 99394,
          "comerciosActivos": 42,
          "vendedoresActivos": 17
        }
      ]
    },
    {
      "domain": "codelpa-peru.youorder.me",
      "name": "Codelpa Perú",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "softys-cencocal.youorder.me",
      "name": "Softys-Cencocal",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 925704,
      "comercios": 18412,
      "comerciosRegistrados": 28970,
      "vendedores": 79,
      "vendedoresYOM": 2,
      "cuentasVendedor": 59,
      "ventaSinIVA": 74107783,
      "primeraOrden": "2021-10-14T16:10:20.000Z",
      "ultimaOrden": "2026-05-04T21:48:35.708Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 20113,
          "ventaSinIVA": 1690490,
          "comerciosActivos": 9395,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 20459,
          "ventaSinIVA": 1682133,
          "comerciosActivos": 9406,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 22245,
          "ventaSinIVA": 1795741,
          "comerciosActivos": 9615,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 20703,
          "ventaSinIVA": 1703630,
          "comerciosActivos": 9602,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 20331,
          "ventaSinIVA": 1766026,
          "comerciosActivos": 9369,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 22245,
          "ventaSinIVA": 1746910,
          "comerciosActivos": 9460,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 19517,
          "ventaSinIVA": 1503680,
          "comerciosActivos": 9392,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 20442,
          "ventaSinIVA": 1707723,
          "comerciosActivos": 9301,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 20863,
          "ventaSinIVA": 1798586,
          "comerciosActivos": 9503,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 18629,
          "ventaSinIVA": 1613248,
          "comerciosActivos": 8890,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 20520,
          "ventaSinIVA": 1666331,
          "comerciosActivos": 9330,
          "vendedoresActivos": 49
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 18879,
          "ventaSinIVA": 1544050,
          "comerciosActivos": 9085,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 968,
          "ventaSinIVA": 63884,
          "comerciosActivos": 945,
          "vendedoresActivos": 46
        }
      ]
    },
    {
      "domain": "softys-dimak.youorder.me",
      "name": "Dimak",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "surtiventas.youorder.me",
      "name": "Surtiventas",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 97076,
      "comercios": 10770,
      "comerciosRegistrados": 11275,
      "vendedores": 77,
      "vendedoresYOM": 2,
      "cuentasVendedor": 91,
      "ventaSinIVA": 29411470,
      "primeraOrden": "2025-06-18T15:17:44.387Z",
      "ultimaOrden": "2026-05-05T10:36:24.541Z",
      "mensual": [
        {
          "year": 2025,
          "month": 6,
          "ordenes": 75,
          "ventaSinIVA": 67689,
          "comerciosActivos": 71,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 967,
          "ventaSinIVA": 94802,
          "comerciosActivos": 764,
          "vendedoresActivos": 5
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1122,
          "ventaSinIVA": 245508,
          "comerciosActivos": 648,
          "vendedoresActivos": 12
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 3506,
          "ventaSinIVA": 880925,
          "comerciosActivos": 2155,
          "vendedoresActivos": 32
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 9846,
          "ventaSinIVA": 2031193,
          "comerciosActivos": 5136,
          "vendedoresActivos": 60
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 11451,
          "ventaSinIVA": 3505597,
          "comerciosActivos": 5807,
          "vendedoresActivos": 63
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 12330,
          "ventaSinIVA": 4339167,
          "comerciosActivos": 6108,
          "vendedoresActivos": 66
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 13151,
          "ventaSinIVA": 5160640,
          "comerciosActivos": 6579,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 12003,
          "ventaSinIVA": 4042011,
          "comerciosActivos": 5903,
          "vendedoresActivos": 65
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 16968,
          "ventaSinIVA": 5133078,
          "comerciosActivos": 7212,
          "vendedoresActivos": 61
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 14940,
          "ventaSinIVA": 3751909,
          "comerciosActivos": 6968,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 717,
          "ventaSinIVA": 158951,
          "comerciosActivos": 684,
          "vendedoresActivos": 54
        }
      ]
    },
    {
      "domain": "elmuneco.youorder.me",
      "name": "El Muñeco",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 2796,
      "comercios": 884,
      "comerciosRegistrados": 7630,
      "vendedores": 10,
      "vendedoresYOM": 2,
      "cuentasVendedor": 16,
      "ventaSinIVA": 194092,
      "primeraOrden": "2025-07-02T20:14:49.488Z",
      "ultimaOrden": "2026-05-04T20:17:03.464Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1,
          "ventaSinIVA": 52,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 142,
          "ventaSinIVA": 8866,
          "comerciosActivos": 112,
          "vendedoresActivos": 2
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 16,
          "ventaSinIVA": 764,
          "comerciosActivos": 16,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 4,
          "ventaSinIVA": 135,
          "comerciosActivos": 1,
          "vendedoresActivos": 1
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 8,
          "ventaSinIVA": 662,
          "comerciosActivos": 7,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 30,
          "ventaSinIVA": 2498,
          "comerciosActivos": 25,
          "vendedoresActivos": 3
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 230,
          "ventaSinIVA": 15851,
          "comerciosActivos": 213,
          "vendedoresActivos": 6
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1285,
          "ventaSinIVA": 95773,
          "comerciosActivos": 639,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 762,
          "ventaSinIVA": 52385,
          "comerciosActivos": 469,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 311,
          "ventaSinIVA": 16612,
          "comerciosActivos": 162,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 7,
          "ventaSinIVA": 493,
          "comerciosActivos": 7,
          "vendedoresActivos": 1
        }
      ]
    },
    {
      "domain": "marleycoffee.youorder.me",
      "name": "Marley Coffee",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 343,
      "comercios": 59,
      "comerciosRegistrados": 2854,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 57,
      "ventaSinIVA": 213309,
      "primeraOrden": "2025-07-15T21:53:35.185Z",
      "ultimaOrden": "2026-05-04T23:18:38.675Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 14,
          "ventaSinIVA": 11122,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 2,
          "ventaSinIVA": 1019,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 2615,
          "comerciosActivos": 3,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 25,
          "ventaSinIVA": 22316,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 49,
          "ventaSinIVA": 34491,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 47,
          "ventaSinIVA": 31061,
          "comerciosActivos": 15,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 30,
          "ventaSinIVA": 20405,
          "comerciosActivos": 14,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 57,
          "ventaSinIVA": 37950,
          "comerciosActivos": 17,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 109,
          "ventaSinIVA": 48442,
          "comerciosActivos": 54,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 7,
          "ventaSinIVA": 3886,
          "comerciosActivos": 7,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisa.youorder.me",
      "name": "Prisa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "caren.youorder.me",
      "name": "Caren",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "coexito.youorder.me",
      "name": "CoÉxito",
      "currency": "USD",
      "nativeCurrency": "COP",
      "sinDatos": false,
      "ordenes": 28151,
      "comercios": 5546,
      "comerciosRegistrados": 22947,
      "vendedores": 92,
      "vendedoresYOM": 0,
      "cuentasVendedor": 141,
      "ventaSinIVA": 26942217,
      "primeraOrden": "2025-11-12T21:55:34.073Z",
      "ultimaOrden": "2026-05-05T03:36:59.847Z",
      "mensual": [
        {
          "year": 2025,
          "month": 11,
          "ordenes": 34,
          "ventaSinIVA": 21954,
          "comerciosActivos": 23,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 763,
          "ventaSinIVA": 738508,
          "comerciosActivos": 365,
          "vendedoresActivos": 10
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 2278,
          "ventaSinIVA": 2591704,
          "comerciosActivos": 1273,
          "vendedoresActivos": 40
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6794,
          "ventaSinIVA": 6350573,
          "comerciosActivos": 3323,
          "vendedoresActivos": 87
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 9253,
          "ventaSinIVA": 8823309,
          "comerciosActivos": 3721,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 8668,
          "ventaSinIVA": 8086430,
          "comerciosActivos": 3803,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 361,
          "ventaSinIVA": 329740,
          "comerciosActivos": 316,
          "vendedoresActivos": 68
        }
      ]
    },
    {
      "domain": "bastien.youorder.me",
      "name": "Bastien",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "sonrie.youorder.me",
      "name": "Sonrie",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 10,
      "comercios": 3,
      "comerciosRegistrados": 2166,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 1,
      "ventaSinIVA": 186,
      "primeraOrden": "2025-09-30T18:05:34.310Z",
      "ultimaOrden": "2026-04-23T19:05:57.930Z",
      "mensual": [
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1,
          "ventaSinIVA": 12,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 76,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6,
          "ventaSinIVA": 99,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "expressdent.youorder.me",
      "name": "ExpressDent",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 6,
      "comercios": 4,
      "comerciosRegistrados": 13567,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 30,
      "ventaSinIVA": 102,
      "primeraOrden": "2026-01-06T19:43:36.968Z",
      "ultimaOrden": "2026-02-05T19:56:42.097Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 5,
          "ventaSinIVA": 101,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1,
          "ventaSinIVA": 1,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisur.youorder.me",
      "name": "Prisur",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 3953,
      "comercios": 1350,
      "comerciosRegistrados": 10784,
      "vendedores": 32,
      "vendedoresYOM": 2,
      "cuentasVendedor": 44,
      "ventaSinIVA": 580630,
      "primeraOrden": "2026-01-20T14:59:35.680Z",
      "ultimaOrden": "2026-05-05T00:25:52.046Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 89,
          "ventaSinIVA": 10346,
          "comerciosActivos": 64,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1034,
          "ventaSinIVA": 150050,
          "comerciosActivos": 665,
          "vendedoresActivos": 24
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1614,
          "ventaSinIVA": 244852,
          "comerciosActivos": 843,
          "vendedoresActivos": 20
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1179,
          "ventaSinIVA": 170516,
          "comerciosActivos": 749,
          "vendedoresActivos": 21
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 37,
          "ventaSinIVA": 4867,
          "comerciosActivos": 36,
          "vendedoresActivos": 7
        }
      ]
    }
  ]
};
