// ============================================================
// YOM Sales Dashboard — Extract Script
// Uso: mongosh "<MONGO_URI>" --quiet --file extract.js > data.js
//
// Extrae para cada cliente configurado en CLIENTS:
//   - Órdenes, comercios distintos, vendedores distintos
//   - Venta sin IVA / con IVA
//   - Desglose mensual
//   - Top 10 vendedores
//   - Rango de fechas
// ============================================================

const STATUS = 'processing';

// Clientes a incluir — { domain, displayName }
const CLIENTS = [
  { domain: 'soprole.youorder.me',          name: 'Soprole' },
  { domain: 'codelpa.youorder.me',           name: 'Codelpa' },
  { domain: 'codelpa-peru.youorder.me',      name: 'Codelpa Perú' },
  { domain: 'softys-cencocal.youorder.me',   name: 'Softys-Cencocal' },
  { domain: 'softys-dimak.youorder.me',      name: 'Dimak' },
  { domain: 'surtiventas.youorder.me',       name: 'Surtiventas' },
  { domain: 'elmuneco.youorder.me',          name: 'El Muñeco' },
  { domain: 'marleycoffee.youorder.me',      name: 'Marley Coffee' },
  { domain: 'prisa.youorder.me',             name: 'Prisa' },
  { domain: 'caren.youorder.me',             name: 'Caren' },
  { domain: 'coexito.youorder.me',           name: 'CoÉxito' },
  { domain: 'bastien.youorder.me',           name: 'Bastien' },
  { domain: 'sonrie.youorder.me',            name: 'Sonrie' },
  { domain: 'expressdent.youorder.me',       name: 'ExpressDent' },
  { domain: 'prisur.youorder.me',            name: 'Prisur' },
];

const data = {
  extractedAt: new Date().toISOString(),
  clients: []
};

for (const client of CLIENTS) {
  const domain = client.domain;

  // --- Totales ---
  const totales = db.orders.aggregate([
    { $match: { domain, status: STATUS } },
    { $group: {
      _id: null,
      ordenes: { $sum: 1 },
      ventaSinIVA: { $sum: '$pricing.totalPrice' },
      ventaConIVA: { $sum: '$pricing.finalTotalPrice' },
      primeraOrden: { $min: { $toDate: '$createdAt' } },
      ultimaOrden: { $max: { $toDate: '$createdAt' } }
    }}
  ]).toArray()[0];

  // Sin datos — incluir igualmente con zeros
  if (!totales) {
    data.clients.push({
      domain,
      name: client.name,
      sinDatos: true,
      ordenes: 0, comercios: 0, vendedores: 0,
      ventaSinIVA: 0, ventaConIVA: 0,
      primeraOrden: null, ultimaOrden: null,
      mensual: [], topVendedores: []
    });
    continue;
  }

  // --- Comercios distintos con orden ---
  const comercios = db.orders.distinct('commerceId', { domain, status: STATUS }).length;

  // --- Vendedores distintos con orden ---
  const vendedoresRaw = db.orders.distinct('sellerId', { domain, status: STATUS });
  const vendedores = [...new Set(vendedoresRaw.flat())].length;

  // --- Desglose mensual ---
  const mensual = db.orders.aggregate([
    { $match: { domain, status: STATUS, createdAt: { $ne: null } } },
    { $group: {
      _id: {
        year:  { $year:  { $toDate: '$createdAt' } },
        month: { $month: { $toDate: '$createdAt' } }
      },
      ordenes:    { $sum: 1 },
      ventaSinIVA: { $sum: '$pricing.totalPrice' },
      ventaConIVA: { $sum: '$pricing.finalTotalPrice' }
    }},
    { $sort: { '_id.year': 1, '_id.month': 1 } }
  ]).toArray().map(m => ({
    year:        m._id.year,
    month:       m._id.month,
    ordenes:     m.ordenes,
    ventaSinIVA: Math.round(m.ventaSinIVA),
    ventaConIVA: Math.round(m.ventaConIVA)
  }));

  // --- Top 10 vendedores ---
  const topVendedores = db.orders.aggregate([
    { $match: { domain, status: STATUS } },
    { $unwind: '$sellerId' },
    { $addFields: { sellerObjId: { $convert: { input: '$sellerId', to: 'objectId', onError: null, onNull: null } } } },
    { $match: { sellerObjId: { $ne: null } } },
    { $group: {
      _id: '$sellerObjId',
      ordenes:     { $sum: 1 },
      ventaSinIVA: { $sum: '$pricing.totalPrice' }
    }},
    { $sort: { ventaSinIVA: -1 } },
    { $limit: 10 },
    { $lookup: { from: 'users', localField: '_id', foreignField: '_id', as: 'user' } },
    { $project: {
      ordenes: 1,
      ventaSinIVA: { $round: ['$ventaSinIVA', 0] },
      nombre: { $arrayElemAt: ['$user.name', 0] },
      email:  { $arrayElemAt: ['$user.email', 0] }
    }}
  ]).toArray().map(s => ({
    id:          s._id.toString(),
    nombre:      s.nombre || 'Sin nombre',
    email:       s.email  || '',
    ordenes:     s.ordenes,
    ventaSinIVA: s.ventaSinIVA
  }));

  data.clients.push({
    domain,
    name:        client.name,
    sinDatos:    false,
    ordenes:     totales.ordenes,
    comercios,
    vendedores,
    ventaSinIVA: Math.round(totales.ventaSinIVA),
    ventaConIVA: Math.round(totales.ventaConIVA),
    primeraOrden: totales.primeraOrden,
    ultimaOrden:  totales.ultimaOrden,
    mensual,
    topVendedores
  });
}

print('// Auto-generated by extract.js — ' + new Date().toISOString());
print('const YOM_DATA = ' + JSON.stringify(data, null, 2) + ';');
